/** Service name (as used in the services catalog / mega menu) -> landing page URL */
export const SERVICE_PAGE_LINKS: Record<string, string> = {
  'Assignment Help': '/assignment-help-uk',
  'Essay Help': '/essay-help',
  'Coursework & Report Help': '/coursework-report-help',
  'Case Study Help': '/case-study-help',
  'Proofreading & Editing': '/proofreading-editing-services',
  'Referencing Help': '/referencing-help',
  'Draft Review & Feedback': '/draft-review-feedback',
  'Presentation Help': '/presentation-help',
  'Dissertation Help': '/dissertation-help-uk',
  'Thesis Help': '/thesis-help',
  'Research Proposal Help': '/research-proposal-help',
  'Literature Review Help': '/literature-review-help',
  'Research Methodology Help': '/research-methodology-help',
  'Data Analysis Help': '/data-analysis-help',
  'SPSS Help': '/spss-help',
  'Excel Data Analysis Help': '/excel-data-analysis-help',
  'NVivo & Thematic Analysis Help': '/nvivo-thematic-analysis-help',
  'Python & Stata Help': '/python-stata-help',
  'PhD Admission & Scholarship Help': '/phd-admission-scholarship-help',
  'Business & Management Assignment Help': '/business-management-assignment-help',
  'MBA Assignment Help': '/mba-assignment-help',
  'Marketing Assignment Help': '/marketing-assignment-help',
  'Finance & Accounting Assignment Help': '/finance-accounting-assignment-help',
  'Healthcare & Nursing Assignment Help': '/healthcare-nursing-assignment-help',
  'Law Assignment Help': '/law-assignment-help',
  'Computing & IT Assignment Help': '/computing-it-assignment-help',
  'Engineering Assignment Help': '/engineering-assignment-help',
};
